import image from './Images/home/ico1.png';
import p1 from './Images/p1.jpg'
const product = [
    {
        id:1,
        name: 'Product 1',
        category: 'category',
        description: 'Description of Product 1',
        price: 20.99,
        image: p1,
        rating:4,
        quantity:1,
      },
      {
        id:2,
        name: 'Product 2',
        category: 'category',
        description: 'Description of Product 2',
        price: 25.99,
        image: image,
        rating:3,
        quantity:1,
      },
      {
        id:3,
        name: 'Product 3',
        category: 'category',
        description: 'Description of Product 3',
        price: 25.99,
        image: image,
        rating:5,
        quantity:1,
      },
      {
        id:4,
        name: 'Product 4',
        category: 'category',
        description: 'Description of Product 4',
        price: 25.99,
        image: image,
        rating:1,
        quantity:1,
      },
      {
        id:5,
        name: 'Product 5',
        category: 'category',
        description: 'Description of Product 5',
        price: 25.99,
        image: image,
        rating:4,
        quantity:1,
      },
      {
        id:6,
        name: 'Product 6',
        category: 'category',
        description: 'Description of Product 6',
        price: 25.99,
        image: image,
        rating:3,
        quantity:1,
      },
      {
        id:1,
        name: 'Product 7',
        category: 'category',
        description: 'Description of Product 7',
        price: 25.99,
        image: image,
        rating:5,
        quantity:1,
      },
      {
        id:7,
        name: 'Product 8',
        category: 'category',
        description: 'Description of Product 8',
        price: 25.99,
        image: image,
        rating:4,
        quantity:1,
      },
  ];
  
export default product;